FROM lscr.io/linuxserver/code-server:4.96.4

RUN  echo "deb [arch=amd64] https://some.repository.url focal main" | sudo tee /etc/apt/sources.list.d/adoptium.list > /dev/null

RUN apt update && apt-get install -y wget apt-transport-https gpg unzip

RUN wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null

RUN echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

RUN apt update && apt-get install -y temurin-21-jdk -y


RUN  apt-get clean && rm -rf /config/* /tmp/* /var/lib/apt/lists/* /var/tmp/*

COPY extensions /root/extensions
RUN  mv /root/extensions/starship /usr/local/bin
RUN  cp /root/extensions/.bashrc  /config
ENV  PATH=/app/code-server/bin:$PATH

RUN code-server --extensions-dir /config/extensions --install-extension /root/extensions/copilot-1.259.1336_vsixhub.com.vsix 
RUN code-server --extensions-dir /config/extensions --install-extension /root/extensions/copilot-chat-0.23.2024120602_vsixhub.com.vsix
RUN code-server --extensions-dir /config/extensions --install-extension /root/extensions/mhutchie.git-graph-1.30.0.vsix 
RUN code-server --extensions-dir /config/extensions --install-extension /root/extensions/humao.rest-client-0.26.0.vsix

RUN code-server --extensions-dir /config/extensions --install-extension vscjava.vscode-java-pack
RUN code-server --extensions-dir /config/extensions --install-extension vmware.vscode-boot-dev-pack

